# Generated by Django 4.0 on 2022-01-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedNews',
            fields=[
                ('date_created', models.DateTimeField(
                    primary_key=True, serialize=False)),
                ('news_list', models.JSONField()),
            ],
        ),
    ]
