# Generated by Django 4.0 on 2022-01-06 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinGeckoCurrencyIDs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.TextField()),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.supportedcurrencies')),
            ],
        ),
    ]
