# Generated by Django 4.0 on 2022-01-06 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_coingeckocurrencyids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coingeckocurrencyids',
            name='id',
        ),
        migrations.AlterField(
            model_name='coingeckocurrencyids',
            name='currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.supportedcurrencies'),
        ),
    ]
