# Generated by Django 3.0.7 on 2021-10-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=120)),
                ('sym', models.CharField(max_length=120)),
                ('feedhandlerTime', models.CharField(max_length=120)),
                ('side', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('qty', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Qsync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
